steps:
  - task: DotNetCoreCLI@2
    displayName: "Backend - Build"
    inputs:
      command: build
      projects: "**/*.csproj"
      arguments: "--configuration Release"
  - task: DotNetCoreCLI@2
    displayName: "Backend - Tests"
    inputs:
      command: test
      projects: "**/*Tests/*.csproj"
      arguments: "--configuration Release"
  - task: Npm@1
    displayName: NPM install Packages
    inputs:
      command: custom
      workingDir: "src/NoteTaker.UI"
      verbose: false
      customCommand: "install --save"
  - task: Npm@1
    displayName: NPM build
    inputs:
      command: custom
      workingDir: "src/NoteTaker.UI"
      verbose: false
      customCommand: "run build:prod"
trigger:
  - master
pool:
  vmImage: "ubuntu-latest"
